---
title: "012325_formatCorumDB"
author: "Martin Gordon"
date: "2025-01-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

CORUM version now available on CORUM DB to download has deviated from the formatting of the version used for `PCprophet` and causes the pipeline to fail
Reformat the newer version of the database to match `PCprophet` specifications

```{r}
library(data.table)
library(ggplot2)
library(magrittr)
library(stringr)
```

Read in the new and old CORUM formats

```{r}
new.corum.dt <- fread('./docs/corumDB_newformat.txt')
old.corum.dt <- fread('./docs/corumDB_oldformat.txt')
corum.5.dt <- fread('./docs/corum.hs.5.1.txt')


old.corum.dt %>% colnames()
corum.5.dt %>% colnames()
fwrite(corum.5.dt, './docs/corum.reformat.hs.5.1.txt', sep='\t')

corum5.tidy <- corum.5.dt[, .(ComplexID=complex_id, ComplexName=complex_name, `subunits(Gene name)`=subunits_gene_name, `subunits(UniProt IDs)`=subunits_uniprot_id, `GO ID`=functions_go_id, `GO description`=functions_go_name)]

fwrite(corum5.tidy, './docs/corum.hs.5.1.formatted.txt', sep='\t')
```

clean the mw uniprot table; currently gene names; convert to mouse uniprot

```{r}
getwd()
mw.uniprot <- fread('./data/Mito_PCprophet/uniprotkb_mouse_AND_reviewed_true_AND_m_2025_03_07.txt')
```


```{r}
old.corum.dt %>% colnames

corum5.tidy

corum.5.dt
old.corum.dt
new.corum.dt
```

```{r}
corum.5.dt[, .(fcgs_description, fcgs_go_name,fcgs_go_id)]
```

