---
title: "022425_makeCorumPPI"
author: "Martin Gordon"
date: "2025-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##

```{r}
library(data.table)
library(magrittr)
library(ggplot2)

source("../../utils/bp_utils/ManageScriptData.R")
```

```{r}
#' returns complex id and name together with gene1, gene2
corumPairs <- function(corum.path = "~/Downloads/corum_humanComplexes.txt"){
  # corum
  corum <- fread (corum.path)
  .allByAll <- function(genes){
    data.table(gene1 = genes)[, .(gene2 = genes), by = gene1][]
  }
  corumPairs <- corum[, .allByAll(unlist(strsplit(subunits_gene_name, ";"))), by = .(complex_id, complex_name)]
  
  corumPairs <- unique(corumPairs[gene1 < gene2, .(gene1, gene2, complex_id, complex_name)])
  return(corumPairs)
}
```


```{r}
ppi <- corumPairs(corum.path = './docs/corum.hs.5.1.txt')

corum.db <- fread('./docs/corum.hs.5.1.txt')
corum.db %>% colnames()

fwrite(corum.db[, .(ComplexID=complex_id, ComplexName=complex_name, `subunits(Gene name)`=subunits_gene_name)], ScriptAndDatedFileName('corum.db.formatted.csv'))

fread('/Users/martingordon/Documents/utils/mg_utils/data/stringDB/9606.protein.links.v12.0.txt.gz')

setnames(ppi, old=c('gene1', 'gene2'), new=c('protA', 'protB'))

corum.ref <- merge(ppi, corum.db[, .(complex_id, complex_name, subunits_gene_name)], by=c('complex_id', 'complex_name')) %>% 
  .[,.(ComplexID=complex_id, ComplexName=complex_name, `subunits(Gene name)`=subunits_gene_name, protA, protB)]

fwrite(corum.ref,  ScriptAndDatedFileName('corum.db.formatted.STRING.csv'))

```

