---
title: "GC01.GC02.shareInWide"
author: "Martin Gordon"
date: "2023-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Share results 

```{r}
library (data.table)
library (ComplexHeatmap)
library (ggplot2)
library (emmeans)
library(stringr)

rotate.x.axis.text <- theme(axis.text.x = element_text(angle = 90,vjust = 0.5, hjust=1))

source("/Users/martingordon/Documents/utils/bp_utils/ManageScriptData.R")
source("/Users/martingordon/Documents/utils//bp_utils/LinearModels.R")
source("/Users/martingordon/Documents/utils/bp_utils/UniprotIDMapping.R")
```

```{r}
mrx2 <- fread('./output/MRX2.mss.pwcomparisons.proc.csv')
qrfpr <- fread('./output/QRFPR.mss.pwcomparisons.proc.csv')


mrx2.wide <- dcast(mrx2, gene+Protein~Label, value.var = c('log2FC', 'pvalue', 'adj.pvalue', 'sig'))
qrfpr.wide <-  dcast(qrfpr, gene+Protein~Label, value.var = c('log2FC', 'pvalue', 'adj.pvalue', 'sig'))

qrfpr.wide

fwrite(mrx2.wide, ScriptAndDatedFileName('mss.mrx2.wide.csv'))
fwrite(qrfpr.wide, ScriptAndDatedFileName('mss.qrfpr.wide.csv'))
```
also share the anova table and contrast of contrasts

```{r}
mrx2.anova <- fread('./output/MRX2.anova.contrasts.csv.gz')
qrfpr.anova <-  fread('./output/QRFPR.anova.contrasts.csv.gz')

mrx2.anova[, gene := multiUniprots2multiGenes(Protein)]
qrfpr.anova[, gene := multiUniprots2multiGenes(Protein)]

mrx2.anova.wide <- dcast(mrx2.anova[term == 'timeStr:pretreat' & !is.na(p.value),], gene+Protein~term, value.var = c('p.value', 'fdr'))
qrfpr.anova.wide <- dcast(qrfpr.anova[term == 'timeStr:pretreat' & !is.na(p.value),], gene+Protein~term, value.var = c('p.value', 'fdr'))

fwrite(mrx2.anova.wide, ScriptAndDatedFileName('mrx2.anova.wide.csv'))
fwrite(qrfpr.anova.wide, ScriptAndDatedFileName('qrfpr.anova.wide.csv'))
```

```{r}
mrx2.emm <- fread('./output/MRX2.emmeans.contrasts.oi.csv')
qrfpr.emm <-  fread('./output/QRFPR.emmeans.contrasts.oi.csv')

qrfpr.emm[,gene:= multiUniprots2multiGenes(Protein)]
mrx2.emm[,gene:= multiUniprots2multiGenes(Protein)]

qrfpr.emm[, fdr:= p.adjust(p.value, method='BH'), by=contrast]
mrx2.emm[, fdr:= p.adjust(p.value, method='BH'), by=contrast]

mrx2.emm.wide <- dcast(mrx2.emm[!is.na(estimate)], gene+Protein~contrast, value.var = c('estimate', 'p.value', 'fdr'))
qrfpr.emm.wide <- dcast(qrfpr.emm[!is.na(estimate)], gene+Protein~contrast, value.var = c('estimate', 'p.value', 'fdr'))

fwrite(mrx2.anova.wide, ScriptAndDatedFileName('mrx2.emm.contrastofcontrast.wide.csv'))
fwrite(qrfpr.anova.wide, ScriptAndDatedFileName('qrfpr.emm.contrastofcontrast.wide.csv'))
```

