---
title: "PCProphet_prepareInput"
author: "Martin Gordon"
date: "2024-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markd

```{r}
library(data.table)
library(magrittr)
library(ggplot2)
library(ComplexHeatmap)


source('~/Documents/utils/bp_utils/ManageScriptData.R')
source('~/Documents/utils/mg_utils/r_utils/SEC_MS_utils.mgupdate.R')
source('~/Documents/utils/bp_utils/UniprotIDMapping.R')
```

tidy and reorder naming convention
```{r}
secms.list <- list(CL = fread('./data/CL-1.txt', header=T),
                   FT = fread('./data/FT-1.txt', header=T),
                   NP_Sonic = fread('./data/NP-Sonic-1.txt', header=T))



newcolorder <- c("Genes","ProteinGroups", as.character(seq(1,72,1) ))


secms.list <- lapply(secms.list, function(x){
  
  x <- x[, ..newcolorder]
  dim(x)
  setnames(x, old=c('Genes', 'ProteinGroups'), new=c('GN', 'ID'))
  return(x)
})
```
Seems some gene names have assigned to more than one ID
Seems some of the genes are collapsed to the same 
```{r}
lapply(secms.list, function(x){
  
  # for sanity check, count the number of dupliate rows in eahc
  dups <- x[,.N, by=GN] %>% 
    .[N> 1, GN]
  
  x[GN %in% dups][order(GN)]
})


secms.list[[3]][grepl(';', GN),]
```
Write out the output files 
```{r}
lapply(seq_along(secms.list), function(x,n,i){

  fwrite(x[[i]], sep='\t', ScriptAndDatedFileName(paste0(n[[i]], '.pcprophet.mat.tsv')))

},x=secms.list, n=names(secms.list))
```


