---
title: "062724_AgonistPWComparisons"
author: "Martin Gordon"
date: "2024-06-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In addition to the earlier contrasts, we also need to run a PW comparison of the agonist vs w/o agonist groups
(same background (cells) in this case, so hopefully cleaner signal?)

```{r cars}
library(magrittr)
library(data.table)
library(circlize)
library(ComplexHeatmap)
library(ggplot2)
library(stringr)
library(randomcoloR)
library(MSstats)
library(ggrepel)
library(readxl)
library(RColorBrewer)
library(cluster) # pam clustering of genes
library(eulerr) # eulerr plot 
library(ggvenn)

source("../../utils/bp_utils/MSstats_Helper_Functions.R")
source("../../utils/bp_utils/ManageScriptData.R")
source ("../../utils/bp_utils/MSstats_V4_Functions.R")
source ("../../utils/bp_utils/UniprotIDMapping.R") #uniprot to gene id mapping
source ("../../utils/bp_utils/enrichmentTestFunctions.R")

source("../../utils/mg_utils/r_utils/IDmapping.R")
source("../../utils/mg_utils/r_utils/plottingHelperFunctions.R")
source("../../utils/mg_utils/r_utils/HelperFunctions.R")

# function to cluster w NA values
clusterWNA <-  function(mat, na.value=0,...){
  
  mat[is.na(mat)] <- na.value
  return(hclust(dist(mat)))
}

View(simplifyEnrichBySimilarUniverseMembership)
```

read in the data 

```{r}

```


Generate contrast matrix for the PW comparisons

```{r}
contrasts.list <- list('+cilia_PM vs -cilia_PM' = data.table(V1="+cilia_PM", V2="-cilia_PM"),
                       '+cilia_ARL13b vs +cilia_PM' = data.table(V1="+cilia_ARL13b", V2="+cilia_PM"), # 
                       '+cilia_ARL13b vs -cilia_ARL13b' = data.table(V1="+cilia_ARL13b", V2="-cilia_ARL13b"), # estimate impact of +/- cilia on cellline
                       '+cilia_SMO vs +cilia_PM' = data.table(V1='+cilia_SMO', V2='+cilia_PM'),
                       '+cilia_GPR161 vs +cilia_PM' = data.table(V1='+cilia_GPR161', V2='+cilia_PM'))


contrasts.mat <- MSstats::MSstatsContrastMatrix(contrasts.list, 
                               conditions = unique(p.quant$GROUP), 
                               labels = names(contrasts.list))
```

```{r}
dp.out <- readRDS('./062424_PWComparisons_data/2024_06_24_dp.out.rds')

f.quant <- setDT(dp.out$FeatureLevelData)

p.quant[, SUBJECT := paste0('batch.',SUBJECT)]

dp.out$FeatureLevelData <- f.quant
dp.out$ProteinLevelData <- p.quant

dp.out$ProteinLevelData[,LogIntensities := newLogInts]
```