---
title: "030725_prepareSECMSinput"
author: "Martin Gordon"
date: "2025-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(magrittr)
library(ggplot2)
library(ComplexHeatmap)

# source Bens scripts so we can do a quick QC assessment of the input data before running
source("../../utils/bp_utils/ManageScriptData.R")
source("~/Documents/utils/bp_utils/SEC_MS_utils.R")
```
# the fraction order seems to match
```{r}
sec.list <- list(ctrl=fread('./data/Mito_PCprophet/Mito_Ctrl_021225.csv'),
                 test=fread('./data/Mito_PCprophet/Mito_Test_021225.csv'))

# check to ensure the order matches expected
lapply(sec.list, function(x){
  
  fractOrder <- sapply(strsplit(colnames(x)[5:ncol(x)], '[._]'), function(y) y[3])
  all(fractOrder == paste0('F', seq(1,ncol(x)-4))) == TRUE
  
})
```

```{r}

```

```{r}
cols.oi <- c(PG.Genes)

sec.list <- lapply(sec.list, function(x){
  
  cols.oi <- c("PG.Genes", "PG.ProteinAccessions", grep('PG.Quantity', colnames(x), value=T))
  print(cols.oi)
  return(x[, ..cols.oi])
  
})
```

```{r}
lapply(sec.list, dim)
lapply(sec.list, function(x){
  
  setnames(x, old=c("PG.Genes","PG.ProteinAccessions"), new=c('GN', 'ID'))
})

```

```{r}
lapply(names(sec.list), function(x){
  
  print(sec.list[[x]])
  fwrite(sec.list[[x]], sep='\t', ScriptAndDatedFileName(paste0(x, '.mito.pcp.in.mat.txt')))
})


# lets actually tidy col names to make srue there are no issues eith spacing
lapply(names(sec.list), function(x){
  
  col.oi <- gsub('[[][0-9]{1,2}[]] ','', colnames(sec.list[[x]]))
  print(col.oi)
  colnames(sec.list[[x]]) <- col.oi
  fwrite(sec.list[[x]], sep='\t', ScriptAndDatedFileName(paste0(x, '.mito.pcp.in.mat.txt')))
})
```
# v low number of proteins recovered in both?
```{r}
lapply(sec.list, dim)
```
read in the corum DB and format correctly before running :

```{r}
corum.dt <- fread('./data/Mito_PCprophet/corum_results.txt')

# lets ty tidy the corum so it meets format expectations
fwrite(corum.dt[, .(ComplexID=complex_id, ComplexName=complex_name, `subunits(Gene name)`=subunits_gene_name, `subunits(UniProt IDs)`=subunits_uniprot_id, `GO ID`=functions_go_id, `GO description`=functions_go_name)], './data/Mito_PCprophet/corum.mm.formatted.txt', sep='\t')

```


Fixt he uniprot file; convert gene name to uniprot and change headers

```{r}
mw.uniprot <- fread('~/Documents/projects/030725_MMuralidharan_SECMS_MitoComparison/data/Mito_PCprophet/uniprotkb_mouse_AND_reviewed_true_AND_m_2025_03_07.txt')

fwrite(mw.uniprot, sep='\t', ScriptAndDatedFileName('uniprotkb_mouse.txt'))
```

```{r}
fread('~/Documents/projects/030725_MMuralidharan_SECMS_MitoComparison/030725_preparePCprophetInput_data/2025_03_10_ctrl.mito.pcp.in.mat') %>% 
  .[,-2] %>% 
  as.matrix(rownames=1) %>% 
  Heatmap(., cluster_columns = F)
```

Read in the DIANN output and create matrices 