---
title: "013125_preparePCProphetInput"
author: "Martin Gordon"
date: "2025-02-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Purpose of this study is to benchmark PCProphet vs Ben's new SEC-MS pipeline
We are three iPSC cell-lines and want to compare the output

```{r}
library(data.table)
library(ggplot2)
library(magrittr)

source("../../utils/bp_utils/ManageScriptData.R")
```

```{r}
indata <-  dir('./data', full.names = T)
sec.dt <- fread(indata)
```

```{r}
sec.list <- list(Parental_1 = dcast(sec.dt[sample == 'Parental_1',], paste0(PG.Genes, '__', PG.ProteinGroups)~fraction, value.var='intensity') %>% as.matrix(rownames=1),
                 Parental_2 = dcast(sec.dt[sample == 'Parental_2',], paste0(PG.Genes, '__', PG.ProteinGroups)~fraction, value.var='intensity')  %>% as.matrix(rownames=1),
                 Parental_3 = dcast(sec.dt[sample == 'Parental_3',], paste0(PG.Genes, '__', PG.ProteinGroups)~fraction, value.var='intensity')  %>% as.matrix(rownames=1),
                 NPC_1 = dcast(sec.dt[sample == 'NPC_1',], paste0(PG.Genes, '__', PG.ProteinGroups)~fraction, value.var='intensity') %>% as.matrix(rownames=1),
                 NPC_2 = dcast(sec.dt[sample == 'NPC_2',], paste0(PG.Genes, '__', PG.ProteinGroups)~fraction, value.var='intensity')%>% as.matrix(rownames=1),
                 Neuron_1 = dcast(sec.dt[sample == 'Neuron_1',], paste0(PG.Genes, '__', PG.ProteinGroups)~fraction, value.var='intensity') %>% as.matrix(rownames=1),
                 Neuron_2 = dcast(sec.dt[sample == 'Neuron_2',], paste0(PG.Genes, '__', PG.ProteinGroups)~fraction, value.var='intensity') %>% as.matrix(rownames=1),
                 Neuron_3 = dcast(sec.dt[sample == 'Neuron_3',], paste0(PG.Genes, '__', PG.ProteinGroups)~fraction, value.var='intensity') %>% as.matrix(rownames=1),
                 Cardio_1 = dcast(sec.dt[sample == 'Cardio_1',], paste0(PG.Genes, '__', PG.ProteinGroups)~fraction, value.var='intensity') %>% as.matrix(rownames=1))


lapply(sec.list, dim)
lapply(sec.list, colnames)
lapply(sec.list, head)

# tidy the neuron 1 low quality fractions
sec.list$Neuron_1[, 21] <- rowSums(sec.list$Neuron_1[, c(20,22)])/2 
sec.list$Neuron_1[, 10] <- rowSums(sec.list$Neuron_1[, c(9,11)])/2

sec.list$Neuron_2 <- cbind(sec.list$Neuron_2, rowSums(sec.list$Neuron_2[, c(63,65)])/2)
colnames(sec.list$Neuron_2) <-  c(colnames(sec.list$Neuron_2)[1:71], '64')

# set the colnames and set NA to 0
sec.f <- lapply(sec.list, function(x){
  
  colOrder <- as.character(seq(1,72,1))
  x <- x[, colOrder]
  print(colnames(x))
  
  x[is.na(x)] <-  0
  return(x)
})

lapply(sec.f, colnames)
```
conver the data to a matrix and fill in missing fraction in one of the set 

```{r}

names(sec.f)

lapply(names(sec.f), function(x){
  
  dt <- setDT(melt(sec.f[[x]], id.vars=rownames(sec.f[[x]])))
  dt[, c('GN', 'ID') := tstrsplit(Var1, '__', keep=c(1,2))]
  dt[, Var1 := NULL]
  
  wide.dt <- dcast(dt, GN+ID~Var2, value.var = 'value')
  colOrder <- c('GN', 'ID', as.character(seq(1,72,1)))
  wide.dt <- wide.dt[, ..colOrder]
  
  fname <- paste0(x, '.pcp.input.mat.csv')
  fwrite(wide.dt, sep='\t', ScriptAndDatedFileName(paste0(x, '.pcp.input.mat.csv')))
})
```

sanitty check and ensure written tab seperated
```{r}
datDir <- dir('./013125_preparePCProphetInput_data', full.names = T)

sec.list <- lapply(datDir, fread, header=T)
datDir
names(sec.list) <- gsub('./013125_preparePCProphetInput_data/2025_01_31_|.pcp.input.mat.csv', '', datDir)

lapply(names(sec.list), function(x){
  
  fwrite(sec.list[[x]], sep='\t', ScriptAndDatedFileName(paste0(x, '.pcp.input.mat.csv')))
})
```

