---
title: "062325_preparePCPInput"
author: "Martin Gordon"
date: "2025-06-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overivew

Given the data that has been shared by Monita, prepare the PCprophet input and run the differential expression analysis. Compare findings with BPs pipeline

```{r}
library(data.table)
library(magrittr)
library(ggplot2)
library(ComplexHeatmap)
library(circlize)
library(stringr)
library(viridis)
library(pracma)
library(magick)
library(eulerr)
library(CCprofiler)

source("../../utils/bp_utils/ManageScriptData.R")
source("../../utils/bp_utils/enrichmentTestFunctions.R")
source("~/Documents/utils/bp_utils/SEC_MS_utils.R")
source("../../utils/bp_utils/UniprotIDMapping.R") # map hu to mm 

customTheme <-  theme_bw() +
  theme(axis.text.x = element_text(angle=90),
        panel.border = element_rect(color = "lightgrey",
                                    fill = NA,
                                    size = 1))
```
Read in the sec.long data table and just use the original intensities as input
```{r}
sec.long <- fread('~/Documents/projects/061425_MMuralidharan_HIVdonor23_SECMS/061725_D123_BPSECMS_pipeline_data/2025_06_18_sec.long.normalized.interpolated.filtered.csv.gz')
sec.long[treatment == 'Challenged_Infected', treatment:= 'Infected']
sec.long[treatment == 'Challenged_Uninfected', treatment := 'Challenged']
sec.long[, sample.old := sample]
sec.long[, sample := paste0(treatment, '_', replicate)]
```
 function to make a PCprophet matrix for input to pipeline
```{r}

makePCprophetMatrix <- function(sec.long, intsCol='originalIntensity'){
  #create ints matrix
  dt <- copy(sec.long)
  dt[is.na(get(intsCol)), (intsCol) := 0]
  mat <- dcast(dt, protein+gene~fraction, value.var=intsCol)
  # reorder/tidy
  setnames(mat, c('protein', 'gene'), c('ID', 'GN'))
  col.order <- c('GN', 'ID', as.character(seq(1,72,1)))
  setcolorder(mat, col.order)
  #return
  stopifnot(colnames(mat) == col.order)
  return(mat)
}

makePCprophetMatrix(sec.long[sample == 'Infected_1',])
```

```{r}
lapply()
```


