---
title: "062425_HIV.d123.secat.prepareInput"
author: "Martin Gordon"
date: "2025-06-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

Prepare input files for the `Secat` SEC-MS tool and run the differential analysis to compare with our tools
Following the tutorial available here: https://www.cell.com/cell-systems/fulltext/S2405-4712(20)30457-9?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS2405471220304579%3Fshowall%3Dtrue
```{r}
library(data.table)
library(magrittr)
library(ggplot2)
library(circlize)
library(stringr)
library(viridis)

source("../../utils/bp_utils/ManageScriptData.R")
source("../../utils/bp_utils/enrichmentTestFunctions.R")
source("~/Documents/utils/bp_utils/SEC_MS_utils.R")
source("../../utils/bp_utils/UniprotIDMapping.R") # map hu to mm 

customTheme <-  theme_bw() +
  theme(axis.text.x = element_text(angle=90),
        panel.border = element_rect(color = "lightgrey",
                                    fill = NA,
                                    size = 1))
```

```{r}

```

