---
title: "0603_edits_tidy"
author: "Martin Gordon"
date: "2024-06-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Rerun of REDItools on the complete dataset
Quality threshold of 20 phred base score
Filter out non-CDS sites and return to Jack 

To try find a high quality set of edits, lets filter out sites with:
i) < 10 WGS reads


## packages

```{r}
library(data.table)
library(ggplot2)
library(magrittr)
library(stringr)
source("../../utils/bp_utils/ManageScriptData.R")
```
Combine the individual datatable into one large datatable
```{r}
files <- dir(path='./data/anno_0603/', pattern='*outTable*', recursive = T, full.names = T)

files.list <- lapply(files, fread, header=T)

names(files.list) <- gsub('./data/anno_0603//|_outTable_anno_[0-9]+.txt','',files)
names(files.list)

# remove data tables with no values

edits.dt <- rbindlist(files.list, idcol='sample', fill=T)
```

```{r}
filtered.dt <- edits.dt[grep('CDS', anno_feat),]
filtered.dt

g <- ggplot(filtered.dt[,.N, by=sample], aes(x=sample, y=N)) +
  geom_bar(stat='Identity') +
  ggtitle('N edits (CDS region & min alt allele frequency >= .01')

g
fwrite(filtered.dt, ScriptAndDatedFileName('RNAedits.out.txt'))



filtered.dt
```

