---
title: "IdentifyConservedSites"
author: "Martin Gordon"
date: "2024-06-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Identifying conserved mammilian sites previously Identifed conserved across human and Xenopus
Goal is to define a 'truth set' that might allow us to find more high quality TP sites 

```{r}
library(data.table)
library(readxl)
library(magrittr)
library(stringr)
source("../../utils/bp_utils/ManageScriptData.R")
```

Read in the conserved sites dataset and convert to bed format

```{r}
getwd()

sites.dt <- rbind(setDT(readxl::read_excel('./docs/12915_2023_1756_MOESM4_ESM.xlsx', sheet=1)),
                  setDT(readxl::read_excel('./docs/12915_2023_1756_MOESM4_ESM.xlsx', sheet=2)), fill=T)


sites.dt
# lets tidy this to the 19 sequences
uniq.sites <- sites.dt[, .(index, hg38, genename.H, genetype.H)] %>% 
  unique()

uniq.sites[, c('chr', 'pos') := tstrsplit(hg38, ':', keep=c(1,2))]

#fwrite(uniq.sites[, .(chr,pos,pos,genename.H)], sep='\t', './docs/conservedSites.bed', col.names = F)
```

