---
title: "101424_makeMajeckDir"
author: "Martin Gordon"
date: "2024-10-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## packages

```{r}
library(data.table)
library(ggplot2)
library(magrittr)
library(readxl)

source('~/Documents/utils/bp_utils/ManageScriptData.R')
```
Read in the mageck sgRNA file and convert to format expected by mageck

```{r}
getwd()
sgRNA.dt <- read_xlsx('./docs/PIK3CA pathway base editing.xlsx', sheet=1) %>%  
  as.data.table()

fwrite(sgRNA.dt[, .(`Sl No`, Guide, Gene)], col.names = F, sep='\t', '/Users/martingordon/Documents/projects/101224_RBabu_CRISPRe_PIK3CA/docs/sgRNA.mageckFormat.txt')

sgRNA.dt
# try another output
fwrite(sgRNA.dt[, .(`Sl No`, Guide, Gene)], col.names = F, sep='\t', '/Users/martingordon/Documents/projects/101224_RBabu_CRISPRe_PIK3CA/docs/sgRNA.mageckFormat.txt')
```




Also write out info on the list of control sgRNA

```{r}
colnames(sgRNA.dt)
sgRNA.dt[, .(...9)] %>%  unique()


sgRNA.dt[Gene == 'non-targeting',.(`Sl No`)]


fwrite(sgRNA.dt[Gene == 'non-targeting',.(`Sl No`)], col.names = F, sep='\t', '/Users/martingordon/Documents/projects/101224_RBabu_CRISPRe_PIK3CA/docs/sgRNA.nonTargetingControls.txt')
```

