---
title: "NPO6_UB.siteInspection"
author: "Martin Gordon"
date: "2023-10-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r}
library(data.table)
library(MSstats)
library(ggplot2)
library(ComplexHeatmap)
library(magrittr)
library(stringr)
library(randomcoloR)

# scripts for PTM analysis
source('../../utils/bp_utils/MSstats_Helper_Functions.R')
source('../../utils/bp_utils/LocatePeptidePtmInProteins.R')
source ("../../utils/bp_utils/MSstats_V4_Functions.R")
source("../../utils/bp_utils/ManageScriptData.R")
source ("/Users/martingordon/Documents/utils/bp_utils/UniprotIDMapping.R") #uniprot to gene id mapping
source ("/Users/martingordon/Documents/utils/bp_utils/enrichmentTestFunctions.R")


rotate.x.axis.text <-   theme(
    axis.text.x = element_text(angle=90, size=7))
```

## UB Site Inspection; 

Earlier analysis of UB sites indiciated a lack of DE sites. Some of the sites we looked at had low counts, at  limit of measurement. We have abundance data for the UB dataset

Questions:
-----
Differences between these datasets? Why is there such a large batch effect? Global differences not even removed after repeated normalization..


Analyse the AB data

```{r}
spec <- fread('./data/AB/20231019_093712_NP06_R1_R5_dirDIA_cEX_AB_MSStatsFormatReport.tsv')

spec[,ID := paste0(Condition,'.',BioReplicate)]
spec[, .N, by=.(Condition,BioReplicate,ID)]
# required column for MSstats
spec[, IsotopeLabelType := "L"]
```


```{r}
# check for multi-measurements
any(spec[, .N, by = .(Run, PeptideSequence, PrecursorCharge)]$N) > 1

ggplot(data=spec, aes(x=log2(Intensity))) +
    geom_histogram(stat='bin', bins=100)

spec <- spec[Intensity > 2^4,]

ggplot(data=spec, aes(x=log2(Intensity))) +
    geom_histogram(stat='bin', bins=100)

```
```{r}
p <- ggplot(spec, aes(x=paste0(Condition,'_',BioReplicate), y=log2(Intensity), fill=Condition)) +
  geom_boxplot() + 
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, size=7))
p

BackupAsPDF(p, 'raw.intensities') 
```
```{r}
p <- spec[, .N, by=.(Condition,BioReplicate,PrecursorCharge)] %>% 
  ggplot(aes(x=paste0(Condition, '_', BioReplicate), y=N, fill=Condition)) +
  geom_bar(stat = 'Identity') +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle=90, size=7))

p
BackupAsPDF(p, 'feature.counts')
```

```{r, fig.width = 10, fig.height = 5}
numColors <- length(unique(spec$Condition))
rColors <- randomcoloR::distinctColorPalette(numColors) 
p <- ggplot (spec, aes (x = interaction(BioReplicate, Condition), fill = Condition)) + geom_bar()  + scale_fill_manual(values = rColors) + theme_bw() + rotate.x.axis.text
p
BackupAsPDF(p, "SpectronautRowCounts_")
```

```{r, fig.width = 10, fig.height = 4}
p <- ggplot (spec[, .(numFeatures = length(unique(paste0(PeptideSequence, PrecursorCharge)))), by =.(BioReplicate, Condition)], 
        aes (x = interaction(BioReplicate, Condition), y= numFeatures, fill = Condition)) +
  geom_col() +
  theme_bw() +
  scale_fill_manual(values = rColors)  +
  rotate.x.axis.text
p
BackupAsPDF(p, "FeatureCounts_")

dp.o
```

## PCA, features
```{r}
featureMat <- dcast (spec,
                     paste0(PeptideSequence, PrecursorCharge)~Condition+BioReplicate, value.var = "Intensity") |> as.matrix(rownames = "PeptideSequence")

featureMat <- featureMat[complete.cases(featureMat), ]

```

```{r}
boxplot (log2(featureMat))
```



```{r}
pcaOut <- prcomp(t(log2(featureMat)))

colInfo <- data.table(colname = colnames(featureMat))
colInfo[,c("npff", "cm", "bt", "rep") := tstrsplit(colname, "_", keep = c(1,2,3,4)) ]
colInfo[, grp := paste(npff,cm,bt, sep = "_")]
colInfo[, npff.cm := paste(npff,cm, sep="_")]


#PCA
pcaDT <- as.data.table(pcaOut$x, keep.rownames=TRUE)
pcaPercentVar <- round(100 * (pcaOut$sdev^2)/sum(pcaOut$sdev^2), 1)
pcaDT <- merge (pcaDT, colInfo, by.x = "rn", by.y = "colname", all.x = TRUE)
#plot first two components
p <- ggplot (pcaDT, aes(x=PC1, y=PC2,  fill = npff.cm, shape=bt)) + 
  geom_point(alpha=1.0, size=4) +
  ggrepel::geom_text_repel(aes(label=rn), show.legend = FALSE, size = 3) +
  theme_bw() + 
  xlab (sprintf ("PC1, %.1f%%", pcaPercentVar[1])) + 
  ylab (sprintf ("PC2, %.1f%%", pcaPercentVar[2])) + 
  ggtitle (sprintf ("PCA %s using %d features (log intensity)", title, nrow(pcaOut))) +
  scale_color_brewer(type = "qual", palette = "Dark2") +
  scale_shape_manual(values = 21:25) +
  #scale_fill_manual(values = c(`05` = "gray", `30` = "black")) +
  guides(fill = guide_legend(override.aes = list(shape =21) ) ,
         color = guide_legend(override.aes = list(shape =21) ) )

p
BackupAsPDF(p, "PCA_Complete_Features")

```


# protein summarization:

```{r}
mssInput <- specFileToCompleteMSstats(spec)
```

```{r}
dp.out<- MSstats::dataProcess(spec, 
                              MBimpute =  FALSE, 
                              featureSubset = "highQuality", 
                              remove_uninformative_feature_outlier = TRUE)

```

```{r}
fwrite (dp.out$FeatureLevelData, "./output/AB.ProteinLevelData.csv")
fwrite (dp.out$FeatureLevelData, "./output/AB.FeatureLevelData.csv.gz")
```


```{r}
p.quant <- fread ("./output/AB.ProteinLevelData.csv")
```


```{r}
prot.mat <- dcast (p.quant, Protein~GROUP+SUBJECT, value.var = "LogIntensities") |> as.matrix (rownames = "Protein")
```

```{r}
nrow(prot.mat)
prot.mat <- prot.mat[complete.cases(prot.mat),]
nrow(prot.mat)
```
Normalised intensities - clear need for additional round of normalisation

```{r}
p <- ggplot(p.quant, aes(x=paste0(GROUP,'_',SUBJECT), y=(LogIntensities), fill=GROUP)) +
         geom_boxplot() +
         theme_classic() +
  theme(axis.text.x = element_text(angle=90, size=7))
p

BackupAsPDF(p, 'normalised.intensities') 
```
Renormalise with TMP and plot again

```{r}
prot.mat <- dcast (p.quant, Protein~GROUP+SUBJECT, value.var = "LogIntensities") |> as.matrix (rownames = "Protein")

#perform tmp normalisation
tmp <- medpolish(prot.mat, na.rm = TRUE) #iteratively subtract row and col median values 

#subtracting column median values from the expression matrix
tmp.dt <- data.table(offset = tmp$col, group_subject = names(tmp$col))

tmp.protQuant <- p.quant[,group_subject := paste0(GROUP,'_',SUBJECT)]
tmp.protQuant[tmp.dt, normalize.offset := i.offset, on = 'group_subject']
tmp.protQuant[, LogIntensities := LogIntensities - normalize.offset]

#fwrite(tmp.protQuant, "./output/AB.ProteinLevelData.tmpNorm.csv")
p.quant <- fread( "./output/AB.ProteinLevelData.tmpNorm.csv")
```

Normalised intensites -TMP

```{r}
p <- ggplot(p.quant, aes(x=paste0(GROUP,'_',SUBJECT), y=(LogIntensities), fill=GROUP)) +
         geom_boxplot() +
         theme_classic() +
  theme(axis.text.x = element_text(angle=90, size=7))
p

BackupAsPDF(p, 'normalised.intensities.tmp') 

```
Seems like there is a large batch effect in the data. 
Need to model this when performing the differential expression analysis

```{r}
# regenerate matrix
prot.mat <- dcast (p.quant, Protein~GROUP+SUBJECT, value.var = "LogIntensities") |> as.matrix (rownames = "Protein")
prot.mat <- prot.mat[complete.cases(prot.mat),]

pcaOut <- prcomp(t(prot.mat))

colInfo <- data.table(colname = colnames(prot.mat))
colInfo[,c("npff", "cm", "bt", "rep") := tstrsplit(colname, "_", keep = c(1,2,3,4)) ]
colInfo[, grp := paste(npff,cm,bt, sep = "_")]
colInfo[, npff.cm := paste(npff,cm, sep="_")]


#PCA
pcaDT <- as.data.table(pcaOut$x, keep.rownames=TRUE)
pcaPercentVar <- round(100 * (pcaOut$sdev^2)/sum(pcaOut$sdev^2), 1)
pcaDT <- merge (pcaDT, colInfo, by.x = "rn", by.y = "colname", all.x = TRUE)
#plot first two components
p <- ggplot (pcaDT, aes(x=PC1, y=PC2,  color = rep)) + 
  geom_point(alpha=1.0, size=4) + 
  ggrepel::geom_text_repel(aes(label=rn), show.legend = FALSE, size = 3) +
  theme_bw() + 
  xlab (sprintf ("PC1, %.1f%%", pcaPercentVar[1])) + 
  ylab (sprintf ("PC2, %.1f%%", pcaPercentVar[2])) + 
  ggtitle (sprintf ("PCA %s using %d features (log intensity)", title, nrow(pcaOut))) +
  scale_color_brewer(type = "qual", palette = "Dark2") +
  scale_shape_manual(values = 21:25) +
  #scale_fill_manual(values = c(`05` = "gray", `30` = "black")) +
  guides(fill = guide_legend(override.aes = list(shape =21) ) ,
         color = guide_legend(override.aes = list(shape =21) ) )

p
#BackupAsPDF(p, "PCA_Complete_Proteins")

```

biotin carboxylase levels 
```{r, fig.width = 10, fig.height = 4}
biotin.carboxylases.up <- c("O00763","P05165","P11498","Q13085","Q96RQ3")

p <- ggplot(p.quant[Protein %in% biotin.carboxylases.up], aes (x = interaction ( SUBJECT, GROUP ), y = LogIntensities, color = Protein)) + geom_line(aes(group = Protein)) + geom_point(aes(shape = as.factor(SUBJECT))) +
  #geom_text(data = protQuant[Protein %in% c("O00763")], aes(label = paste0(GROUP, ".", SUBJECT), size = paste0(GROUP, "_", SUBJECT) %in% problemRuns)) +
  rotate.x.axis.text

p
BackupAsPDF(p, "BiotinCarboxylaseLevels_")
```
heatmaps of the data clear issues with batch effects even after two rounds of normalization,  include batch term in lm
```{r}

# cluster with missing values
clusterwNA <- function(x, na.val=0){
  
  x[is.na(x)] <- 0
  hclust(dist(x))
}

p.mat <- dcast(p.quant, Protein~interaction(GROUP,gsub('batch.','',SUBJECT)), value.var = 'LogIntensities') %>% 
  as.matrix(rownames='Protein')

# subtract median expression vlaues per row
#subMat <- sweep(p.mat, 1, apply(p.mat, 1, median, na.rm=T))
subMat <- p.mat[sample.int(nrow(p.mat),2000),]

rownames(subMat) <- multiUniprots2multiGenes(rownames(subMat))


batch <- str_extract(colnames(p.mat), '[0-9]{1}$')
bt.status <- str_extract(colnames(p.mat), 'BT[0-9]{2}')
np.status <- str_extract(colnames(p.mat), 'NP[0-9]{2}')
cm.status <- str_extract(colnames(p.mat), 'CM[0-9]{2}')
group     <- str_extract(colnames(p.mat), 'NP[0-9]{2}_CM[0-9]{2}')

batch.col <- randomcoloR::distinctColorPalette(length(unique(batch)))
names(batch.col) <- unique(batch)
bt.col <- randomcoloR::distinctColorPalette(length(unique(bt.status)))        
names(bt.col) <- unique(bt.status)
group.col <- randomcoloR::distinctColorPalette(length(unique(group)))      

ha <- HeatmapAnnotation(group = group, bt=bt.status, batch=batch, annotation_name_side = "right", col= list(group = c('NP00_CM00'='red', 'NP00_CM15' = 'blue', 'NP30_CM00'='green', 'NP30_CM15'='orange'), bt.status = bt.col, batch=batch.col))

  #generate heatmap
hm <- Heatmap(subMat,
        top_annotation = ha,
        cluster_rows = clusterwNA(subMat),
        show_row_names = TRUE,
        row_title = sprintf("%d Proteins", nrow(subMat)),
        na_col = 'grey',
        column_names_gp = gpar(fontsize = 6),
        row_names_gp = gpar(fontsize = 2.5),
       # column_title = paste0(' heatmap'),
        name = "Int. vs Median")
 
BackupAsPDF(hm,"intensityHeatmap", dimensions=c(8,6))

 
# subtract median expression vlaues per row
subMat <- sweep(p.mat, 1, apply(p.mat, 1, median, na.rm=T))
subMat <- subMat[sample.int(nrow(subMat), 2000),]

rownames(subMat) <- multiUniprotSites2multiGeneSites(rownames(subMat))

  #generate heatmap
hm <- Heatmap(subMat,
        top_annotation = ha,
        cluster_rows = clusterwNA(subMat),
        show_row_names = F,
        row_title = sprintf("%d Proteins", nrow(subMat)),
        na_col = 'grey',
        column_names_gp = gpar(fontsize = 6),
        row_names_gp = gpar(fontsize = 2.5),
       # column_title = paste0(' heatmap'),
        name = "Int. vs Median")
hm
BackupAsPDF(hm,"scaled.intensity.heatmaps", dimensions=c(8,6))
```
Pairwise Contrasts
----
Run a pairwise comparison of each of the different groups

```{r}
mat.dimnames <- list(rnames='NP30_CM00_BT00-NP00_CM00_BT00', #NP vs ctrl 
                     cnames=c("NP00_CM00_BT00","NP00_CM00_BT02","NP00_CM15_BT00","NP00_CM15_BT02","NP30_CM00_BT00","NP30_CM00_BT02","NP30_CM15_BT00","NP30_CM15_BT02"))


dp.contrasts <- matrix(data= c(-1,0,0,0,1,0,0,0), nrow = 1, dimnames=mat.dimnames)
dp.contrasts <- rbind(dp.contrasts, c(0, -1,0,0,0,1,0,0))
rownames(dp.contrasts)[2] <- 'NP30_CM00_BT02-NP00_CM00_BT02' #NP vs ctrl in presence of bt
dp.contrasts <- rbind(dp.contrasts, c(-1, 0,1,0,0,0,0,0))
rownames(dp.contrasts)[3] <- 'NP00_CM15_BT00-NP00_CM00_BT00' #CM vs ctrl
dp.contrasts <- rbind(dp.contrasts, c(0, -1,0,1,0,0,0,0))
rownames(dp.contrasts)[4] <- 'NP00_CM15_BT02-NP00_CM00_BT02' #cm15 vs control in presence of bt
dp.contrasts <- rbind(dp.contrasts, c(0, 0,0,0,-1,0,1,0))
rownames(dp.contrasts)[5] <- 'NP30_CM15_BT00-NP30_CM00_BT00' #cm15 + Np vs NP 
dp.contrasts <- rbind(dp.contrasts, c(0,0,0,0,0,-1,0,1))
rownames(dp.contrasts)[6] <- 'NP30_CM15_BT02-NP30_CM00_BT02' #cm15 + np vs NP in presence of bt

dp.contrasts <- rbind(dp.contrasts, c(-1, 0,0,0,0,0,1,0))
rownames(dp.contrasts)[7] <- 'NP30_CM15_BT00-NP00_CM00_BT00' #cm15 + Np vs control; interaction?

dp.contrasts <- rbind(dp.contrasts, c(0, -1,0,0,0,0,0,1))
rownames(dp.contrasts)[8] <- 'NP30_CM15_BT02-NP00_CM00_BT02' #cm15 + Np in presence of bt vs bt control; interaction?

dp.contrasts
```
Run MSStats pairwise comparisons

```{r}
#read back feature data and remove the poor quality sample
fwrite (dp.out$FeatureLevelData, "./output/AB.FeatureLevelData.csv.gz")


f.quant <- fread("./output/AB.FeatureLevelData.csv.gz")
#fwrite(f.quant, './NPO6.rerun.feature.lvl.quant.rmoutlier.csv.gz')

# add batch to SUBJECT header and include in the design matrix
p.quant[, SUBJECT := paste0('batch.',SUBJECT)]
f.quant[, SUBJECT := paste0('batch.',SUBJECT)]

dp.out$FeatureLevelData <- f.quant
dp.out$ProteinLevelData <- p.quant

# run msstats correcting for batch 
mss <- groupComparison(contrast.matrix=dp.contrasts, data=dp.out)
mss.dt <- setDT(mss$ComparisonResult)

#fwrite(mss.dt, './output/mss.contrasts.ab.csv.gz')
```

```{r}
mss <- fread('./output/mss.contrasts.ab.csv.gz')

#clean the res
mss <- mss[issue != 'completeMissing',] %>% 
  .[!is.infinite(abs(log2FC)), ] %>% 
  .[,gene := multiUniprotSites2multiGeneSites(Protein)] %>% 
  .[,sig := 'not'] %>% 
  .[abs(log2FC) > 0.58 & adj.pvalue < 0.05, sig := ifelse(log2FC > 0, 'up', 'down')]


mss[pvalue < 0.05,]

sig.prots <- mss[sig != 'not', (Protein)]

ggplot(p.quant, aes(x=interaction(GROUP,SUBJECT), y=LogIntensities, fill=GROUP)) + geom_violin()
```

```{r}
col.pal <- distinctColorPalette(2)


g <- ggplot(mss[sig!='not', .N, by=.(Label,sig)], aes(x=sig, y=N, fill=sig)) +
  geom_col() +
  scale_fill_manual(values=col.pal) +
  facet_wrap(~Label) + 
  ggtitle('N signifcant hits FC +/- 50% & adj.pvalue < 0.05') +
  theme_bw() +
  theme(strip.text.x = element_text(size = 5))

g

BackupAsPDF(g, 'NsigHits.adj.pval<0.05.allSamples')
```



