---
title: "R Notebook"
output: html_notebook
---
Prepare the MIST interactor set for AF3 run

```{r}
library(magrittr)
library(ggplot2)
library(data.table)
library(readxl)

# source afew useful commands 
source("../../utils/bp_utils/ManageScriptData.R")
source ("../../utils/bp_utils/UniprotIDMapping.R")
source ("../../utils/mg_utils/r_utils/plottingHelperFunctions.R")
```



```{r}
mist.scores.list <- list(HEK = as.data.table(read_xls('./docs/NIHMS358189-supplement-Supplementary_Data_2.xls', sheet=1)),
                         Jurkat = as.data.table(read_xls('./docs/NIHMS358189-supplement-Supplementary_Data_2.xls', sheet=2)))


lapply(names(mist.scores.list), function(x){
  

  new_repo <- paste0(x, '_MiST_Reproducibility')
  new_abu <- paste0(x, '_MiST_Abundance')
  new_spe <- paste0(x, '_MiST_Specificity')
  new_mist <- paste0(x, '_MiST_score')
  
  setnames(mist.scores.list[[x]], old=c('Reproducibility', 'Abundance', 'Specificity','MiST score'), new=c(new_repo, new_abu, new_spe, new_mist))
})

# combine mist scores for the two cell lines
# mist scores doesnt distinguish the groups...
mist.scores.dt <- merge(x=mist.scores.list[[1]][,.(Bait, Prey,HEK_MiST_Reproducibility,HEK_MiST_Abundance,  HEK_MiST_Specificity
,HEK_MiST_score)], mist.scores.list[[2]][,.(Bait,Prey,Jurkat_MiST_Reproducibility,Jurkat_MiST_Abundance, Jurkat_MiST_Specificity, Jurkat_MiST_score)], by=c('Bait', 'Prey'), all.x=T, all.y=T)


mist.scores.list[[```

Create a job table for use with the alphafold scripr

```{r}
fwrite(mist.scores.dt[Jurkat_MiST_score >= 0.75 | HEK_MiST_score >= 0.75,][, .(.I,Bait,Prey)], ScriptAndDatedFileName('af.hivHu.jobtable.csv'))
```

