---
title: "221124_plotsOfInteractors"
author: "Martin Gordon"
date: "2024-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(magrittr)
library(ggplot2)
library(data.table)
library(readxl)

# source afew useful commands 
source("../../utils/bp_utils/ManageScriptData.R")
source ("../../utils/bp_utils/UniprotIDMapping.R")
source ("../../utils/mg_utils/r_utils/plottingHelperFunctions.R")
```

```{r}
af.dt <- fread('201124_AFInteractiorsIntegration_data/2024_11_21_af.hiv.interactors.MiSTscores.iMEX.anno.csv')
```

```{r}
ggplot(af.dt, aes(x=Bait, y=ipTM_mean, fill=Bait)) +
  geom_boxplot() +
  geom_hline(yintercept=0.75, color='red') +
  theme_bw() +
  theme(axis.text.x = element_text(angle=90))

ggplot(af.dt, aes(x=Bait, y=plddt2_mean, fill=Bait)) +
  geom_boxplot() +
  geom_hline(yintercept=70, color='red') +
  theme_bw() +
  theme(axis.text.x = element_text(angle=90))

ggplot(af.dt[, .(avg_iptm = mean(ipTM_mean, na.rm=T), avg_plddt2 = mean(plddt2_mean, na.rm=T)), by=.(Bait)], aes(x=avg_plddt2, y=avg_iptm, color=Bait)) +
  geom_point() +
  theme_bw()

```
Split the datasdet into the MIST high confidence and 

```{r}
af.dt[, mistHighCSet := ifelse(HEK_MiST_score >= .7|Jurkat_MiST_score >= .75, 'yes' ,'no')]

af.dt

ggplot(af.dt, aes(x=Bait, y=ipTM_mean, fill=mistHighCSet)) +
  geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(angle=90))


af.dt[Bait == 'CA' & !is.na(HEK_MiST_score), max(HEK_MiST_score)]
```


