---
title: "021025_MYCN_AF3ppi"
author: "Martin Gordon"
date: "2025-02-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(ggplot2)
library(magrittr)
library(ggrepel)
library(stringr)
library(ComplexHeatmap)
library(circlize)
library(viridis)
library(RColorBrewer)
library(hrbrthemes) # visually nice set of themes
library(patchwork)
library(showtext)
library(seqinr)
library(readxl)
library(tidymodels)
library(ggridges)
library(RColorBrewer)


# fonts needed for hrbrthemes
library(extrafont)
font_import()
loadfonts()

# directly from google font
sysfonts::font_add_google("Roboto Condensed")
showtext_auto()

source("../../utils/bp_utils/MSstats_Helper_Functions.R")
source("../../utils/bp_utils/ManageScriptData.R")
source ("../../utils/bp_utils/enrichmentTestFunctions.R")
source ("../../utils/bp_utils/UniprotIDMapping.R")

source ("../../utils/mg_utils/r_utils/IDmapping.R")
source ("../../utils/mg_utils/r_utils/plottingHelperFunctions.R")
source("../../utils/mg_utils/r_utils/CRISPR_Functions.R")

# function to cluster w NA values
clusterWNA <-  function(mat, na.value=0,...){
  
  mat[is.na(mat)] <- na.value
  return(hclust(dist(mat)))
}

customTheme <- theme_ipsum_rc() +
  theme(panel.border = element_rect(color = "lightgrey", 
                                    fill = NA, 
                                    size = 1),
        axis.text.x = element_text(angle=90)
        )

#set one
col.pal <- getQualitativePalette(n=13)
#col.pal <- randomcoloR::distinctColorPalette(k=13)
```

AF3 models 
```{r}
af.summary.dt <- fread('./output/012425_firstRUn_summaryScores.csv')

af.summary.dt[, ppi := gsub('[.]seed.+$', '', model)]
af.summary.dt[, c('proteinA', 'proteinB') := tstrsplit(toupper(ppi), '__', keep=c(1,2))]
af.summary.dt[, c('geneA', 'geneB') := .(multiUniprots2multiGenes(proteinA, species='HUMAN'), multiUniprots2multiGenes(proteinB, species='HUMAN'))]
af.summary.dt[, gene_ppi := paste(geneA, geneB, sep='__')]
```
make a summary datatable 
```{r}
summary.dt <- af.summary.dt[, .(mean_ptm= mean(ptm, na.rm=T), mean_iptm=mean(iptm, na.rm=T)), by=.(ppi,gene_ppi, proteinA, proteinB, geneA, geneB)]
summary.dt[geneA == 'PTEN']
```


