---
title: "111024_makePCPInput"
author: "Martin Gordon"
date: "2024-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## packages

```{r}
library(data.table)
library(magrittr)
library(ggplot2)
```

```{r}
source('~/Documents/utils/bp_utils/ManageScriptData.R')
source('~/Documents/utils/mg_utils/r_utils/SEC_MS_utils.mgupdate.R')
source('~/Documents/utils/bp_utils/UniprotIDMapping.R')
```
Load in the data from Antoine and format for PCP
```{r}
#secms.list <- list(ctrl = fread('./data/Biosep_MDAMB468_CTRL_2_Report.tsv'), 
#                   ptxl = fread('./data/Biosep_MDAMB468_PTXL_2_Report.tsv'), 
#                   vrst = fread('./data/Biosep_MDAMB468_VRST_1_Report.tsv')
#                   )

secms.list <- list(ctrl = fread('/Users/martingordon/Downloads/Biosep_MDAMB468_CTRL2_Report.tsv'), 
                   ptxl = fread('/Users/martingordon/Downloads/Biosep_MDAMB468_PTXL_2_Report.tsv'), 
                   vrst = fread('/Users/martingordon/Downloads/Biosep_MDAMB468_VOR_1_Report.tsv')
                   )


# fix ordering of one of the SECMS samples
setcolorder(secms.list[[2]], neworder=c(seq(1,6,1), 77, seq(7,76,1)))


# looks ok now 
lapply(secms.list, function(x){
  gsub('_','', stringr::str_extract(colnames(x), '_F[0-9]{1,2}_')) 
})


# looks ok now 
lapply(secms.list, function(x){
  head(x)
})
```
make the PCP matrices
```{r}

secms.mat.list <- lapply(secms.list, function(x){
  
 mat <-  generatePCProphetMatrix(x, gene="PG.Genes", uniprot="PG.UniProtIds")
 return(mat)
})
       

```
Looks good, write to file and run on remote server
```{r}
#looks good
lapply(secms.list, function(x){
  x[PG.Genes %in% c('RAMACL', 'RBM47', 'TTC26'),]})

lapply(secms.mat.list, function(x){
  x[GN %in% c('RAMACL', 'RBM47', 'TTC26'),]})


lapply(secms.list, function(x){
  dups <- x[duplicated(PG.Genes), unique(PG.Genes)]
  print(dups)
  x[PG.Genes %in% dups,]
})


lapply(secms.mat.list, function(x){
  dups <- x[duplicated(GN), unique(GN)]
  print(dups)
  x[GN %in% dups,]
})
```
```{r}
lapply(seq_along(secms.mat.list), function(x, n,i){
  
  submat <- x[[i]][GN != '',]
  fwrite(submat, sep='\t', ScriptAndDatedFileName(paste0(n[[i]],'.rerun.mat.txt')))
  
},x=secms.mat.list, n=names(secms.mat.list))


fread('~/Documents/projects/100824_AForget_BCancerCells_SECMS/101124_makePCProphetInput_data/2024_10_11_ctrl.rerun.mat.txt')


```


