---
title: "R Notebook"
output: html_notebook
---

Pulling out CDKs from the abundance/PH datasets

```{r}
library("RColorBrewer") 
library(data.table)
library(dplyr)
library(magrittr)
library(ggplot2)
library (ComplexHeatmap)
library(MSstats)
library(OmnipathR)
library(VennDiagram)

# load bens util scripts for the analysis
source ("../../utils/bp_utils/MSstats_V4_Functions.R")
source("../../utils/bp_utils/ManageScriptData.R")
source("../../utils/bp_utils/LocatePeptidePtmInProteins.R")
source ("../..//utils/bp_utils/MSstats_Helper_Functions.R")
source ("../../utils/bp_utils/UniprotIDMapping.R") #uniprot to gene id mapping
source ("../../utils/bp_utils/enrichmentTestFunctions.R")
source ("../../utils/bp_utils/KinaseActivityScores.R")

WriteSessionInfo()
WriteInstalledPackages()


```
Load kinasesummary scores and summary data

```{r}
k.s.s <- fread('/Users/martingordon/Documents/projects/060123_DSwaney_AshworthPH/060123_DSwaney_AshworthPH_data/2023_06_02_kinaseSummaryScores.csv')
k.s.d <- fread('/Users/martingordon/Documents/projects/060123_DSwaney_AshworthPH/060123_DSwaney_AshworthPH_data/2023_06_02_kinaseSubstrateData.csv')

print(k.s.s)
print(k.s.d)
```

Load kinasesummary scores and summary data

```{r}
cdk.list <- c('CDK2', 'CDK4', 'CDK6', 'CDK12',  )
cdk.list <- paste0('CDK', seq(1,20, by=1))
cdk.list <- cdk.list[cdk.list != c("CDK5", "CDK11", "CDK12", "CDK14")] 
cdk.list

kss.filter <- k.s.s[ grepl( "CDK",CTRL_GENE_NAME), .(Label, CTRL_GENE_NAME, N, sites)]
kss.filter
# CDK sites ordered by number of target sites per condition
fwrite(kss.filter[order(Label,-N)], 
fwrite(kss.filter[order(Label,-N)], ScriptAndDatedFileName("cdk-PH-hits.csv.gz"))

```

