---
title: "090125_PH_PWcomparisons"
author: "Martin Gordon"
date: "2025-01-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(data.table)
library(ggplot2)
library(magrittr)
library(ggrepel)
library(stringr)
library(ComplexHeatmap)
library(circlize)
library(MSstats)
library(viridis)
library(ggbeeswarm)
library(RColorBrewer)
library(hrbrthemes) # visually nice set of themes
library(patchwork)
library(showtext)
library(seqinr)
library(readxl)

source("../../utils/bp_utils/MSstats_Helper_Functions.R")
source("../../utils/bp_utils/ManageScriptData.R")
source ("../../utils/bp_utils/MSstats_V4_Functions.R")
source ("../../utils/bp_utils/UniprotIDMapping.R") #uniprot to gene id mapping
source ("../../utils/bp_utils/enrichmentTestFunctions.R")
source ("../../utils/bp_utils/MSstats_V4_Functions.R")


source("../../utils/mg_utils/r_utils/plottingHelperFunctions.R")
source("../../utils/mg_utils/r_utils/msstats_helperFunctions.R")


# function to cluster w NA values
clusterWNA <-  function(mat, na.value=0){
  
  mat[is.na(mat)] <- na.value
  return(hclust(dist(mat)))
}

#set one
col.pal <- getQualitativePalette(n=13)
#col.pal <- randomcoloR::distinctColorPalette(k=13)

# fonts needed for hrbrthemes
library(extrafont)
font_import()
loadfonts()

# directly from google font
sysfonts::font_add_google("Roboto Condensed")
showtext_auto()
```

Read in the researched data
```{r}
hu.list <- list(msstats=fread('./data/010425_ViralProtsInDBSearch/MRC5_PH/MSstats_20250104_180149_JB_MRC5_PH_rerun_010425_Report.tsv'),
                keys=fread('./data/010425_ViralProtsInDBSearch/MRC5_PH/JB_MRC5_PH_rerun_010425_ConditionSetup.tsv'))

bat.list <-  list(msstats=fread('./data/010425_ViralProtsInDBSearch/RFe_PH/MSstats_20250104_194351_JB_RFe_PH_rerun_010425_Report.tsv'),
                  keys=fread('./data/010425_ViralProtsInDBSearch/RFe_PH/JB_RFe_PH_rerun_010425_ConditionSetup.tsv'))
```

3 reps per group
```{r}
hu.list[[2]][,.N, by=Condition][order(Condition)]
bat.list[[2]][,.N, by=Condition][order(Condition)]

# sanity check to ensure the metadata keys match the msstats file....
# TRUE for both... can drop the metadata after ormating
identical(hu.list[[2]][,.(Run=`Run Label`, Condition, BioReplicate=Replicate)], unique(hu.list[[1]][,.(Run, Condition, BioReplicate)]))
identical(bat.list[[2]][,.(Run=`Run Label`, Condition, BioReplicate=Replicate)], unique(bat.list[[1]][,.(Run, Condition, BioReplicate)]))
```

```{r}
# bioreps only unique per group
hu.list[[1]]$Condition %>% unique()
bat.list[[1]]$Condition %>% unique()
```

```{r}

```


