---
title: "031425_checkGFF"
author: "Martin Gordon"
date: "2025-03-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## read in fasta and check if edits match the expected

```{r}
library(data.table)
library(ggplot2)
library(seqinr)
library(magrittr)

source("../../utils/bp_utils/ManageScriptData.R")
```

```{r}
fa.in <- seqinr::read.fasta('./data/Eli_data/D.paellei.fasta',as.string = T, forceDNAtolower = F, whole.header = T)


fa.dt <- data.table(header=names(unlist(fa.in)),
                    seq=unlist(fa.in))
  
fa.dt[, c('name', 'oftStart', 'orfEnd') := tstrsplit(header, '\\t', keep=c(1,3,5))]  
fa.dt[, header := NULL]
```


```{r}
edits <- fread('./data/Eli_data/D.paellei.edits.gff')

fa.dt <- merge(fa.dt, y=edits[V3=='snp',.(name=V1,site=V4)], by='name')

fa.dt[, oftStart := as.numeric(oftStart)]
fa.dt[, `:=`(refBaseFromStart = substr(seq,site, site),
             refBaseFromOrf  = substr(seq,oftStart+site, oftStart+site))
             ]

fa.dt$refBaseFromStart %>% unique()
```

Ok, looks like these indx are taken from first pos of the sequence... now check my gff using the new edit sites and see if these also match up...

```{r}
lited.edits <- fread('./data/Eli_data/edits.refSeqmapping.snpOnly.gff', skip = 3)
lited.edits


refseq.fa <- seqinr::read.fasta('./data/wynton_downloads/dpea.pipelineProcessed.genome.transcripts.fa', as.string = T, forceDNAtolower = F, whole.header = T)

refseq.dt <- data.table(header=names(unlist(refseq.fa)),
                    seq=unlist(refseq.fa))

refseq.dt <- merge(refseq.dt, lited.edits[,.(header=V1, editSite=V4)], by='header')
refseq.dt[, refBaseFromStart := substr(seq,editSite, editSite)]

# what about the T's possible edits on the -ve refernce?
g <- ggplot(refseq.dt[,.N, by=refBaseFromStart], aes(x=refBaseFromStart, y=N, fill=refBaseFromStart)) +
  geom_bar(stat='identity') +
  ggtitle('Reference base in lifted genome') +
  scale_fill_brewer(type='qual') +
  annotate(geom='text', x=3.5,y=60000, size=5, label=paste('% mapped:',round(71436/82714,2))) +
  theme_bw()
g
BackupAsPDF(g, 'liftedSites.refBases.barplot')
```
plot proportion of mapped edits
```{r}
melt(data.table(total=82714,mapped=71436))




ggplot(melt(data.table(total=82714,mapped=71436)), aes(x=variable, value=value)) +
  geom_bar(stat='identity')
       
       
```

