---
title: "060225_newPlotsForKroganWeekly"
author: "Martin Gordon"
date: "2025-06-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview 

Change the color code for a couple of the receptors

```{r}
library(data.table)
library(magrittr)
library(ggplot2)
library(stringr)
library(ggbeeswarm)
library(ggrepel)
library(patchwork)
library(readxl)
library(circlize)
library(ComplexHeatmap)
library(randomcoloR)
library(scales) #for muted colors
library(eulerr)

# this is for the Venn diagram plots
library(ggvenn)
library(ggVennDiagram) # main diff to above is you can quantify overlapping regions

#Ben utils
source("/Users/martingordon/Documents/utils/bp_utils/ManageScriptData.R")
source("/Users/martingordon/Documents/utils//bp_utils/LinearModels.R")
source("/Users/martingordon/Documents/utils/bp_utils/UniprotIDMapping.R")
source ("/Users/martingordon/Documents/utils/bp_utils/enrichmentTestFunctions.R")


# helper scripts for module/network export etc
source ("/Users/martingordon/Documents/utils/mg_utils/r_utils/HelperFunctions.R")


# function to cluster w NA values
clusterWNA <-  function(mat, na.value=0){
  
  mat[is.na(mat)] <- na.value
  return(hclust(dist(mat)))
}

```

new color palettes 
```{r}
# order here is DOR, KOR, MOR, MRX2, MRX4, NK1R, NPFFR1, NPY1R, PTGR1 PTGR4, QRFPR
col.pal <- c("#D57AC7","#8DDDE1","#A1E4AC","#6EE766","#CEDF5F","#DEC5D2","#85A693","#DBBB7C","#7D9AD6","#D96A6E","#A94FDD")  #"#999933" '#DDCC77' "grey"
# this is Qiopngyus new palette
receptorColors <- c(
DOR = "#99CCFF",
KOR = "#66CCFF",
MOR = "#3399FF",
MRX2 = "#b470ba",
MRX4 = "#FF6666",
NK1R = "#FF9900",
NPFFR1 = "#9EBCDA",
NPY1R = "#0099CC",
PTGER1 = "#FFCCCC",
PTGER4 = "#85CB9C",
QRFPR = "#cc93c2")
```

read in files and select the clusters of interest
```{r}
protQuant <- fread('~/Documents/projects/082423_QLi_GPR_WGCNA/010725_plotsForKroganWeekly_data/2025_06_02_proteinQuant.anno.csv.gz')

cluster.oi <- c('cluster1', 'cluster6')
```

line chart of chosen receptors with divergent color scale 
```{r}
cluster.oi <- c('cluster1', 'cluster6')

g <- ggplot(protQuant[Cluster %in% cluster.oi,], aes(x=timeStr, y=vsTimeZero, group=receptor, color=receptor, label=receptor)) + 
  geom_smooth(stat = 'summary', fun.y = median, se =TRUE, show.legend = T, aes(fill=receptor, alpha=0.2)) +
  scale_color_manual(values = receptorColors) + 
  scale_fill_manual(values = receptorColors) + 
  ggtitle('Median expression vs Time 0') +
  geom_hline(yintercept = 0, linetype=2, alpha=0.6) +
  stat_summary(data=protQuant[Cluster %in% cluster.oi & timeStr == '30',], stat = 'summary', fun.y = median, geom='text', size=3,
                   hjust = -.05, position = position_nudge(x = .05)) +
  #geom_dl()
  labs(x='timepoint (mins)', y="Intensity (log2)") +
  facet_wrap(~cluster_label, scales='free_y', ncol=3) +
  theme_classic() +
  #scale_x_discrete(expand=c(0,0.03)) +
  theme(
  # panel.spacing.x = unit(2.5, "lines"),
   plot.margin = margin(0.1, 2.6, 0.1, 0.1, "cm"), 
   strip.text = element_text(size = 6)) +
  guides(color=FALSE,
         fill=FALSE,
         alpha=FALSE) +
    coord_cartesian(clip='off') # allow labels to enter canvas boundaries

g 
BackupAsPDF(g, 'clusters.oi.wSE.scales.free.newreceptorCol.linechart')
```
plot of the positive controls

```{r}
genes.oi <- c('ARRB2', 'EEA1','PRKD2')

g <- ggplot(protQuant[gene %in% genes.oi,], aes(x=timeStr, y=vsTimeZero, group=receptor, color=receptor, label=receptor)) + 
  geom_smooth(stat = 'summary', fun.y = mean, se =TRUE, show.legend = T, aes(fill=receptor, alpha=0.2)) +
  scale_color_manual(values = receptorColors) + 
  scale_fill_manual(values = receptorColors) + 
  ggtitle('ARBB2, EEA1 & PKRD2 mean expression vs Time 0') +
  geom_hline(yintercept = 0, linetype=2, alpha=0.6) +
  stat_summary(data=protQuant[gene %in% genes.oi & timeStr == '30',], stat = 'summary', fun.y = median, geom='text', size=1.5,
                   hjust = -.05, position = position_nudge(x = .05)) +
  labs(x='timepoint (mins)', y="Intensity (log2)") +
  facet_wrap(~gene, ncol=3) +
  theme_classic() +
  #scale_x_discrete(expand=c(0,0.03)) +
  theme(
   axis.title.x = element_text(size=8),
   axis.text.x=element_text(size=6),
   axis.title.y = element_text(size=8),
   axis.text.y=element_text(size=6),
   plot.title = element_text(size=8, face = 'bold'),
   panel.spacing.x = unit(2.5, "lines"),
   plot.margin = margin(0.1, 2.6, 0.1, 0.1, "cm"), 
   strip.text = element_text(size =6)) +
   guides(color=FALSE,
         fill=FALSE,
         alpha=FALSE) +
  coord_cartesian(clip='off') # allow labels to enter canvas boundaries
g 
BackupAsPDF(g, 'posControls.wSE.scalesFixed.newreceptorCol.linechart', dimensions = c(7.3,2))


g <- ggplot(protQuant[gene %in% genes.oi,], aes(x=timeStr, y=vsTimeZero, group=receptor, color=receptor, label=receptor)) + 
  geom_smooth(stat = 'summary', fun.y = mean, se =TRUE, show.legend = T, aes(fill=receptor, alpha=0.2)) +
  scale_color_manual(values = receptorColors) + 
  scale_fill_manual(values = receptorColors) + 
  ggtitle('ARBB2, EEA1 & PKRD2 mean expression vs Time 0') +
  geom_hline(yintercept = 0, linetype=2, alpha=0.6) +
  #stat_summary(data=protQuant[gene %in% genes.oi & timeStr == '30',], stat = 'summary', fun.y = median, geom='text', size=1.5,
  #                 hjust = -.05, position = position_nudge(x = .05)) +
  labs(x='timepoint (mins)', y="Intensity (log2)") +
  facet_wrap(~gene, ncol=3) +
  theme_classic() +
  scale_x_discrete(expand=c(0,0.03)) +
  theme(
   legend.title = element_text(size = 6),  # Adjust legend title size
   legend.text = element_text(size = 5),   # Adjust legend text size
   legend.key.size = unit(0.3, "cm"),       # Adjust legend key size
   axis.title.x = element_text(size=8),
   axis.text.x=element_text(size=6),
   axis.title.y = element_text(size=8),
   axis.text.y=element_text(size=6),
   plot.title = element_text(size=8, face = 'bold'),
   panel.spacing.x = unit(2.5, "lines"),
   plot.margin = margin(0.1, 2.6, 0.1, 0.1, "cm"), 
   strip.text = element_text(size =6)) +
   guides(color=guide_legend(override.aes=list(fill='white', size = 1)),
          fill=FALSE,
          alpha=FALSE) +
  coord_cartesian(clip='off') # allow labels to enter canvas boundaries
g 

BackupAsPDF(g, 'posControls.wSE.scalesFixed.receptorCol.wLegend.linechart', dimensions = c(7.3,2))
```
```{r}

```

