---
title: "gpcr.wgcna.redo"
author: "Martin Gordon"
date: "2023-09-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R repeat of the WGCNA workflow
Adjust the generation

```{r}
library(data.table)
library(ggplot2)
library(ComplexHeatmap)
library(WGCNA)
library(magrittr)
library(preprocessCore) # quantile normalisation
library(stringr)
library(matrixStats)
library(simplifyEnrichment)
library(fmsb)
library(readxl)
library(ggbeeswarm)
library(ggrepel)

source("/Users/martingordon/Documents/utils/bp_utils/ManageScriptData.R")
source("/Users/martingordon/Documents/utils//bp_utils/LinearModels.R")
source("/Users/martingordon/Documents/utils/bp_utils/UniprotIDMapping.R")
source ("/Users/martingordon/Documents/utils/bp_utils/enrichmentTestFunctions.R")
```

## WGCNA GPCR proteins
extract the top 

```{r}
# read in exp data
p.quant <- fread('data/2022_08_17_ProteinLevelData.lib.csv.gz')

# read in DEA results for filtering
mss <- fread('data/2022_08_31_NiceFitsPower3.csv')

p.quant$GROUP %>%  unique()
```

```{r}
# fix the groups with an underscore in them MOR_LG and MOR_DAMGO to MOR.DAMGO
p.quant[, GROUP := gsub ("_([A-Z])", ".\\1", GROUP)]
# add some new identifier cols
p.quant[, `:=`(timeStr = str_extract(GROUP,'[0-9]{2}$'),
               receptor = gsub("_[0-9]{2}$", '', p.quant$GROUP)
               )]
```

Does this data need a second round of normalisation?
Assumption is the data is normalised
```{r}
group.noi <- p.quant[!GROUP %like% c("DOR|KOR|MOR|MRX2|MRX4|NK1R|NPFFR1|NPY1R|PTGER1|PTGER4|QRFPR|DOR"),unique(GROUP)]
group.noi

p.quant <- p.quant[!GROUP %in% group.noi, ]
p.quant <- p.quant[!GROUP %like% "MOR.LG94",]

p.quant$GROUP %>%  unique()
```
```{r}
p.quant[, batchControlled := LogIntensities - median(LogIntensities, na.rm = TRUE), by = .(Protein, receptor, SUBJECT)]
p.quant[, vsTimeZero := batchControlled - mean(batchControlled[timeStr == timeStr[!is.na(batchControlled)][1] ]), by = .(Protein, receptor)]


p.mat <- dcast(p.quant, Protein~GROUP+SUBJECT, value.var = 'vsTimeZero') %>%  as.matrix(rownames="Protein")




BackupAsPDF(draw(hm,column_title=sprintf("%d proteins WGCNA input vsT0 (no qnorm & batch corrected)", nrow(p.mat.f)),
           column_title_gp=grid::gpar(fontsize=16)), 'wgcna.input.vsT0', dimensions = c(9,12)) 
```
