---
title: "010625_sgRNAlibPrep"
author: "Martin Gordon"
date: "2025-01-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(ggplot2)
library(magrittr)
library(ggrepel)
library(stringr)
library(ComplexHeatmap)
library(circlize)
library(MSstats)
library(viridis)
library(ggbeeswarm)
library(RColorBrewer)
library(hrbrthemes) # visually nice set of themes
library(patchwork)
library(showtext)


source("../../utils/bp_utils/MSstats_Helper_Functions.R")
source("../../utils/bp_utils/ManageScriptData.R")
source ("../../utils/bp_utils/MSstats_V4_Functions.R")
source ("../../utils/bp_utils/UniprotIDMapping.R") #uniprot to gene id mapping
source ("../../utils/bp_utils/enrichmentTestFunctions.R")
source ("../../utils/bp_utils/MSstats_V4_Functions.R")


# for generating the scatterplots
source("../../utils/mg_utils/r_utils/plottingHelperFunctions.R")
```

Pull out the sgRNA library file 

Read in the library prep file
```{r}
sgRNA.dt <-  fread("/Users/martingordon/Documents/projects/010225_ABanerjee_IBD_CRISPR/docs/sgRNA_library.txt")

sgRNA.dt[, idx := .I]
sgRNA.dt
sgRNA.dt[, sgRNA := paste0('sg_', idx)]

sgRNA.lib.dt <- sgRNA.dt[, .(sgRNA, sequence=`sgRNA Target Sequence`, gene=`Target Gene Symbol`)]
sgRNA.control.dt <- sgRNA.lib.dt[gene == 'Non-Targeting Control', .(sgRNA)]
```
Write out the two files and use in the MAGECK count command

```{r}
#fwrite(sgRNA.lib.dt, col.names = F, sep='\t', ScriptAndDatedFileName('sgRNA.library.txt'))
#fwrite(sgRNA.control.dt, col.names = F, sep='\t', ScriptAndDatedFileName('sgRNA.nontargetingControls.txt'))
```

