---
title: "100424.FormatPCPDatabase"
author: "Martin Gordon"
date: "2024-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Format a database in perturbSeq structure so we can use it with PCProphet to detect clusters

```{r library}
library(data.table)
library(magrittr)
library(ggplot2)

source("/Users/martingordon/Documents/utils/bp_utils/ManageScriptData.R")
source("/Users/martingordon/Documents/utils/bp_utils/UniprotIDMapping.R")
source ("/Users/martingordon/Documents/utils/bp_utils/enrichmentTestFunctions.R")
source("/Users/martingordon/Documents/utils/bp_utils/ManageScriptData.R")
```
Read in the CORUMDB and compare with the cluster set
```{r}
corum.dt <- fread('./data/humanComplexes.txt')
clusters.dt <-  fread('./data/KOLF2-SrongPerturbation-Clusters.csv')
```

```{r}
corum.dt[`Cell line` == 'None']
corum.dt %>%  head()
corum.dt %>%  colnames()
corum.dt[`Protein complex purification method` == 'None']
```

```{r}
# ok the genes  belong to distinct groups, so 
clusters.dt[,.N, by=gene_target] %>% 
  .[N>1]

clusters.dt[,ComplexID := cluster+1]
clusters.dt[, ComplexName := paste('Cluster', ComplexID, sep='_')]
clusters.dt[, Organism :=  'Human']
clusters.dt[, Synonyms :=  'None']
clusters.dt[, `Cell line` :=  'None']


clusters.dt

clusters.dt[, .(ComplexID, ComplexName, Organism, Synonyms, `Cell line`, `subunits(Gene name)`=)]



clusters.dt[, .(geneIDs = paste(gene_target, collapse=';' ,nMembers=)), by=cluster]
```

