---
title: "061025_fileInspection"
author: "Martin Gordon"
date: "2025-06-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

Read in the Spectronaut files for the phage and see if the measured values are incorrect

```{r}
library(data.table)
library(magrittr)
library(ggplot2)
```
file 
```{r}
files <- list(inf141_3_pep = "~/Library/CloudStorage/Box-Box/Phage_SEC-MS_Data/Replicate\ 3/Rep3_141Infected/20250417_210547_IJK_032125_Rep3_141Infected_Peptide_Report.tsv",
              inf141_3_prot = "~/Library/CloudStorage/Box-Box/Phage_SEC-MS_Data/Replicate\ 3/Rep3_141Infected/20250417_210547_IJK_032125_Rep3_141Infected_Protein_Report.tsv")
```



```{r}
sec.list  <- lapply(files, fread)
sec.list[['inf141_3_pep']][PG.ProteinLabel == 'B7VG67']
sec.list[['inf141_3_prot']][PG.ProteinGroups == 'B7VG67']

sec.list[['inf141_3_pep']][, PG.ProteinGroups := PG.ProteinLabel]
sec.list[['inf141_3_pep']]


convertToMatrix <- function(x){
  
  cols.oi <- c('PG.ProteinGroups', grep('PG.Quantity|EG.TotalQuantity', colnames(x), value=T))
  dt.wide <- x[, ..cols.oi]
  dt.long <- setDT(reshape2::melt(dt.wide, id.vars='PG.ProteinGroups'))
  setnames(dt.long, new=c('feature', 'fraction', 'intensity'))
  print(dt.long)
  dt.long[ intensity == 'Filtered' | is.nan(intensity), intensity := NA] # keep everything consistent
  dt.long[, intensity := as.numeric(intensity)]
  mat <- as.matrix(dcast(dt.long, feature~fraction, value.var = 'intensity', fun.aggregate = sum, na.rm=T), 
                   rownames='feature')
  #return(mat)
  
}
sec.mat <- lapply(sec.list , convertToMatrix)
```

```{r}
# 28455 files affected
corrupted.files <- fread('./_wynton_group_krogan.txt', header = F)
nrow(corrupted.files)
corrupted.files

corrupted.files[, user := tstrsplit(V1, '[/]', keep=5)]
corrupted.files[,.N, by=user] # just apelin files affected


# how many directories?
corrupted.files[, dir.name := dirname(V1)]
corrupted.files[,.N, by=dir.name] #23k folders affected..
corrupted.files[!grepl('/wynton/group/krogan/apelin/AlphaFold', dir.name)]

corrupted.files[, parent.dir := paste0(unlist(tstrsplit(V1, '[/]', keep=c(1,2,3,4,5))), collapse = '/'), by=.I]
corrupted.files
```

