---
title: "071125_lysisPrepShinyData_Inspection"
author: "Martin Gordon"
date: "2025-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

```{r}
library(data.table)
library(magrittr)
library(ggplot2)
library(ComplexHeatmap)
library(stringr)
library(viridis)
library(pracma) # needed for the peak finding algorithm
library(magick)
#library(UniProt.ws) #cant load this packge; get naming conventions another way

# source Bens scripts so we can do a quick QC assessment of the input data before running
source("../../utils/bp_utils/ManageScriptData.R")
source("../../utils/bp_utils/UniprotIDMapping.R") # map hu to mm 
source("~/Documents/utils/bp_utils/enrichmentTestFunctions.R")

# flag consec proteins
source("~/Documents/utils/bp_utils/SEC_MS_utils.localMods.R")
source("~/Documents/utils/bp_utils/SEC_MS_utils.R")
```


```{r}
sec.long <- fread('./071125_LysisPrepShiny/data/2025_02_11_SEC_Long_normalized.csv.gz')

sec.long
de.dt <- fread('./071125_LysisPrepShiny/data/2025_01_21_TreatmentContrasts_PairwiseContrasts.csv.gz')

sec.long[, sumIntensity := log2(sum(intensity, na.rm=T)), by=.(protein, sample)]
  # create max and total scaled intensity column
sec.long[, intensity_totalScaled := intensity/(sum(intensity, na.rm = TRUE)), by= .(sample, protein)]
sec.long[, intensity_maxScaled := intensity/(max(intensity, na.rm = TRUE)), by= .(sample, protein)]


fwrite(sec.long, ScriptAndDatedFileName('lysisPrep.csv.gz'))
```

