---
title: "092024_AFFstructuresFilter"
author: "Martin Gordon"
date: "2024-09-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(stringr)
library(magrittr)
library(ggplot2)

source('~/Documents/utils/bp_utils/ManageScriptData.R')
```

Just get top scoring models 
```{r}
AFscores.dt <- fread('./data/allScores.csv')
setnames(AFscores.dt, new=c('source', 'ptm'))


AFscores.dt[, model := str_extract(source, 'model_[0-9]{1}')]
AFscores.dt[, protein := tstrsplit(source, '/', keep=6)]

# get the best model of each protein, keep those only > .5 ptm 
AFscores.f <- AFscores.dt[, .SD[which.max(ptm)], by=.(protein)] %>% 
  .[ptm >= 0.5] %>% 
  .[, .(paste0(protein, '_', model), source)]


AFscores.f[, source := sub('.+output', '/wynton/group/krogan/mgordon/projects/083024_JMoen_ProteinswEdits_AF2/output', source)]
AFscores.f[, source := sub('scores.csv[:]','', source)]

#fwrite(AFscores.f, './data/AFscores.filtered.csv')
```
100424 Update to the new scores

```{r}
af.scores.dt <- fread('./data/100424.allScores.csv')

```

calculate average PTM score per protein
```{r}
setnames(af.scores.dt, new=c('source', 'ptm'))
af.scores.dt[, protein := tstrsplit(source,'/', keep=3)]
af.scores.dt[, avg.ptm := mean(ptm, na.rm=T), by=.(protein)]
af.scores.dt[, model := gsub('model_', '', stringr::str_extract(source, 'model_[1-5]{1}'))]

#  histogram
g <- ggplot(af.scores.dt, aes(x=ptm)) +
  geom_histogram(boundary=0, binwidth = 0.01) +
  geom_vline(xintercept=0.5) +
  ggtitle('Distribution of AF PTM scores')

g
BackupAsPDF(g, 'AF.ptm.scores.histogram')


# avg scores
g <- ggplot(af.scores.dt, aes(x=avg.ptm)) +
  geom_histogram(boundary=0, binwidth = 0.01) +
  geom_vline(xintercept=0.5) +
  ggtitle('Distribution of AF PTM scores')

g
BackupAsPDF(g, 'AF.ptm.scores.histogram')


# create a rank plot with model scores 
g <- ggplot(af.scores.dt, aes(x=reorder(protein, avg.ptm), y=ptm, color=ifelse(ptm >= 0.5, 'yes', 'no'), shape=model)) +
  geom_point() +
  geom_hline(yintercept=0.5) +
  scale_color_manual(values=c('yes'='red', 'no'='black')) +
  ggtitle('Proteins ranked by average ptm') +
  xlab('Protein') +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, size=3))


BackupAsPDF(g, 'ranked.ptm.dotplot', dimensions=c(26,12))
```
Could it just be these are easily modelled?

```{r}
summary(af.scores.dt)


# too many; only plot the passing subset
g <- ggplot(af.scores.dt[avg.ptm > 0.75,], aes(x=reorder(protein, avg.ptm), y=ptm, color=ifelse(ptm >= 0.5, 'yes', 'no'), shape=model)) +
  geom_point() +
  scale_color_manual(values=c('yes'='red', 'no'='black')) +
  ggtitle('Proteins ranked by average ptm') +
  xlab('Protein') +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, size=5))

g

BackupAsPDF(g, 'ranked.ptm.threshold.dotplot', dimensions=c(18,12))
```

```{r}
g <- ggplot(af.scores.dt[avg.ptm > 0.75,], aes(x=reorder(protein, avg.ptm), y=ptm, color=ifelse(ptm >= 0.5, 'yes', 'no'), shape=model)) +
  geom_point() +
  geom_hline(yintercept=0.5) +
  scale_color_manual(values=c('yes'='red', 'no'='black')) +
  ggtitle('Proteins with avg ptm > .75') +
  xlab('Protein') +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, size=4))

g
BackupAsPDF(g, 'ranked.ptm.Threshold.dotplot', dimensions=c(18,12))
```
```{r}
fwrite(af.scores.dt, ScriptAndDatedFileName('af.scores.all.csv'))

# write out only the avg scores
af.scores.dt

summary.dt <- af.scores.dt[, .SD[which.max(ptm)], by=protein] %>% 
  .[ptm >= 0.5,.(protein, model, ptm, avg.ptm)]

summary.dt
fwrite(summary.dt, ScriptAndDatedFileName('af.scores.summary.csv'))
```

