---
title: "wgcna-test"
author: "Martin Gordon"
date: "2023-07-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages 

```{r}
install.packages("WGCNA")   # WGCNA is available on CRAN
library(WGCNA)
library(genefilter)
```


## Attempting to create co-expression clusters from the DEA proteins, phosphoproteins and RNA molecules

```{r}
#read in the cleaned data from the 3 datasets
# read in the clean omics files
rna.ab.clean <- fread('./output/rna_ab.clean.csv.gz')
rna.ab.clean[, omics :='rna']
rna.ab.clean[, adj.pvalue := p.adjust(pvalue, method = 'BH')]

prot.ab.clean <- fread('./output/prot_ab.clean.csv.gz')
prot.ab.clean[, omics := 'p.ab']
prot.ph.clean <- fread('./output/prot_ph.clean.csv.gz')
prot.ph.clean[, omics := 'p.ph']

omics.clean <- list(rna_ab = rna.ab.clean,
                    prot_ab = prot.ab.clean,
                    prot_ph = prot.ph.clean)
```


From each dataset, extract significant features

```{r}
sig.omics.clean <- lapply(omics.clean, function(x){
  x[adj.pvalue < 0.05 & log2FC > log2(1.5)]
})

```


Transpose the datasets 

```{r}
sig.omics.clean <- lapply(sig.omics.clean, function(x){
  x <- t(x)
})


```




