---
title: "120524_Alphafold3_functions"
author: "Martin Gordon"
date: "2024-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Collection of alphafold 3 functions for modifying file formats

```{r}
library(data.table)
library(magrittr)
library(ggplot2)
library(jsonlite)
library(digest)

# to handle the MSA format
library(Biostrings)
library(seqinr)

source("../../utils/bp_utils/ManageScriptData.R")
```
Used to format the host-pathogen set correctly
```{r}
hpi.dt <- fread('/Users/martingordon/Documents/utils/mg_utils/data/phi-base_current.csv', header = T) %>% 
  .[-c(1),]

# hpi database is manually curated, so perlaps a little more complete?
hpi.dt[,.(`Record ID`, PHI_MolConn_ID, ProteinID, Gene_name, )]

hpi.db2.dt <- fread('~/Documents/utils/mg_utils/data/hpidb2.mitab/hpidb2.mitab_plus.txt')
hpi.db2.dt %>%  head()
```
lets use the hpidb2 input; we need an identifer that matches to boht


```{r}
hpi.db2.dt %>% head()
hpi.db2.dt %>% colnames()
```
```{r}
filtered.dt <- hpi.db2.dt[, .(`# protein_xref_1`, `protein_xref_2`,protein_xref_1_display_id, protein_xref_2_display_id, protein_taxid_1, protein_taxid_2, detection_method, database_identifier, confidence, protein_seq1, protein_seq2)]


filtered.dt %>% colnames()
setnames(filtered.dt, new=c('host_uniprot', 'pathogen_uniprot', 'host_display', 'pathogen_display', 'host_taxID', 'pathogen_taxID', 'detectionMethod', 
                            'database_identifier', 'confidence', 'host_proteinSeq' ,'pathogen_proteinSeq'))

filtered.dt[, host_uniprot := gsub('uniprotkb:','', host_uniprot)]
filtered.dt[, pathogen_uniprot := gsub('uniprotkb:','', pathogen_uniprot)]
filtered.dt[, host_taxID := stringr::str_extract(host_taxID, 'taxid:[0-9]+')]
filtered.dt[ , pathogen_taxID := stringr::str_extract(pathogen_taxID, 'taxid:[0-9]+')]
filtered.dt[, host_taxID := gsub('taxid:', '', host_taxID)]
filtered.dt[, pathogen_taxID := gsub('taxid:', '', pathogen_taxID)]


fwrite(filtered.dt, ScriptAndDatedFileName('filtered.hpi.db.csv'))


fread('~/Documents/projects/120324_MGordon_MGordon_AF3_pipeline/121024_HPI_DBPreparation_data/2024_12_16_filtered.hpi.db.csv')
```

