---
title: "R Notebook"
output: html_notebook
---

Script to loop through PTM analysis

```{r}
library (data.table)
library (ComplexHeatmap)
library (ggplot2)
library(tidyverse)
rotate.x.axis.text <- theme(axis.text.x = element_text(angle = 90,vjust = 0.5, hjust=1))

source ("../../utils/bp_utils/MSstats_V4_Functions.R")
source("../../utils/bp_utils/ManageScriptData.R")
source("../../utils/bp_utils/LocatePeptidePtmInProteins.R")
WriteSessionInfo()
WriteInstalledPackages()
```

Configure paths to files

```{r setup}

getwd()
#path to files on your machine
path <- "/Users/martingordon/Documents/projects/071023_QLi_DARPA"

#fasta_old <- paste0(path, "/dorPea_CDS_AA_All_Edits_noDup.fasta") 
fasta_new <- paste0(path,'/2023-05-08_dorPea_CDS_AA_Single_Tryptic_noDup.fasta')  #use this as dups removed

f_input <- dir(path = paste0(path, '/2023-05-09-noimput'), pattern = "*.xls", recursive = FALSE, full.names = TRUE) 
k_input <- dir(path = path, pattern = "keys.txt", recursive = FALSE, full.names = TRUE)

input <- data.frame(f_input,k_input)

rm(f_input)
input <- input %>% 
  mutate(ptm_type=as.factor(str_extract(f_input, pattern="AcK|MeK|PH|UB"))) %>% 
  arrange(ptm_type)

rm(f_input)
rm(k_input)
```

```{r preprocess-func}
preprocessSpec <- function(spec_f,keys_f){

  #fread stores as data.table by default
  spec <- fread(spec_f)
  keys <- fread(keys_f)

  #add semicolon if required 
  spec[, ProteinName := gsub ("(?<![_>])PAC", ";PAC", ProteinName, perl = TRUE)] #uses perl regex v with negative lookbehind to negate -/> characters 


  # for some reason the '>' was kep in the protein names here.  Remove those:
  spec[, ProteinName := gsub (">", "", ProteinName)]

  # apply Condition, BioReplicate from keys to spec
  spec[keys , Condition := i.Condition , on = c(Run = "RawFile")] #overwrite condition col w values from keys file, match run col in spec to rawfile col in keys
  spec[keys , BioeReplicate := i.BioReplicate , on = c(Run = "RawFile")]
  
  return(spec)
  setnames(spec) = dat_name
}

```